### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by shujaatak** [ThomArmax/arduino-qt-creator-plugin#1]
Build instructions would be much helpful for the potential contributors.

By the way, is this plugin ready for working with Arduino projects?

**Comment by ThomArmax** [comment]
Hi @shujaatak 

Thanks.

This project is in WIP, and not functional, and I have figured out that will require a lot of time (which I have not ...)

To build this project, you have to download the QtCreator sources and build the plugin against.

You can refer to
- https://doc.qt.io/qtcreator-extending/getting-and-building.html
- https://doc.qt.io/qtcreator-extending/first-plugin.html

**Comment by shujaatak** [comment]
Any directions for the potential contributors to make it functional?

**Comment by ThomArmax** [comment]
I have started this alone when I was bored and unfortunately I have no contact who could contribute on that ....
